# Generated by Django 5.2.10 on 2026-01-28 18:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('planned_duration', models.PositiveIntegerField(help_text='Dakika cinsinden')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('completed', 'Tamamlandı'), ('partial', 'Kısmen Tamamlandı'), ('distracted', 'Dikkat Dağıldı')], max_length=20, null=True)),
                ('difficulty', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('actual_duration', models.PositiveIntegerField(blank=True, help_text='Dakika cinsinden', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
